- hosts: localhost

  vars_files:
    - vars/main.yml

  tasks:
  - name: Get repos from Azure Devops
    when: ansible_lint_reporter_content_src_type|lower == 'ado'
    block:
    - name: Run Azure DevOps tasks
      ansible.builtin.include_tasks: tasks/azure_devops.yml
      tags:
        - ado
        - clone
    module_defaults:
      ansible.builtin.uri:
        force_basic_auth: yes
        user: git
        password: "{{ ado_personal_access_token }}"

  - name: Print content source directory
    when: ansible_lint_reporter_content_src_type|lower == 'directory'
    ansible.builtin.debug:
      var: ansible_lint_reporter_root_dir

  - name: Install python package requirements
    pip:
      name: 
        - ansible-lint
        - jmespath
      state: present
    become: yes
    tags: lint

  - name: Find content
    ansible.builtin.find:
      paths: "{{ ansible_lint_reporter_root_dir }}"
      patterns: "{{ ansible_lint_reporter_roles_glob }}"
      recurse: no
      file_type: directory
      excludes: "{{ ansible_lint_reporter_root_dir_excludes }}"
    register: r_roles
    become: yes
    tags: lint

  - name: Create destination directory
    ansible.builtin.file:
      path: "{{ playbook_dir }}/reports"
      state: directory
      mode: 0755
    tags: lint

  - name: Lint repository
    ansible.builtin.shell: "ansible-lint -f codeclimate {{ role }} > {{ playbook_dir }}/reports/{{ role | basename }}.json"
    register: r_lint
    changed_when: r_lint.rc in [0,1,2]
    failed_when: r_lint.rc not in [0,1,2] 
    loop: "{{ r_roles.files | json_query('[].path') | list }}"
    loop_control:
      loop_var: role
    become: yes
    tags: lint

  - name: Get role reports
    set_fact:
      f_reports: "{{ lookup('fileglob', playbook_dir + '/reports/*.json').split(',') }}"
    tags: template

  - name: Template reports.js
    ansible.builtin.template:
      src: reports.js.j2
      dest: "{{ playbook_dir }}/dist/js/reports.js"
      mode: 0644
    tags: template

  - name: Template index.html
    ansible.builtin.template:
      src: index.html.j2
      dest: "{{ playbook_dir }}/dist/index.html"
      mode: 0644
    tags: template
